language: java
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
notifications:
  email: false
env:
  global:
    - LAPIS_DEPLOY=https://github.com/LapisBlue/Deploy.git
    - DEPLOY_ROOT=/tmp/lapis/deploy
    - secure: KaNtP9g/EvsE/cB/SFkfKrbGa8DfBaRkIuKJPK2uArtgN0AGiZ+biugu8x0VY3MFfbLtBfWFipIV15NHVgkeb7b5fFtNvGUaXOke4sLAqe9EXiUNufqlWPXmIKqK+lKOS7guSAaLpovnVDrBUkJF1IHOl9iXKARrFtw1D0Dn2ys=
after_success:
  # TODO: Publish Commons to Maven repo
  - git clone $LAPIS_DEPLOY $DEPLOY_ROOT && $DEPLOY_ROOT/javadocs.sh commons "./gradlew javadoc -x :SpongeAPI:javadoc" build/docs/javadoc
