language: java
jdk:
- openjdk6
- openjdk7
- oraclejdk7
- oraclejdk8
notifications:
  email: false
env:
  global:
    secure: Od8YNVi6KSYrqRbuD0j6b6om0JicHuJv459/BeWM5JDMMISIlZsYA8A3vHmoIt5MhjlTz7AccFt9pvWLvIytc2xvBNtHbO7ZS1hwF4krKADUC0CS5uaRI3YX/lJFx6Gmy0ePWWU6/JUvqVwKqmVEvL4yUc1+4PP0R+vckNHUydU=
after_script:
  - python travis_after_all.py
  - ./javadocs